
const people = [
  { type: "man", pronoun: "his" },
  { type: "woman", pronoun: "her" },
  { type: "child", pronoun: "their" },
  { type: "dog", pronoun: "its" },
  { type: "cat", pronoun: "its" },
  { type: "grandma", pronoun: "her" },
  { type: "grandpa", pronoun: "his" },
  { type: "baby", pronoun: "their" },
  { type: "teenager", pronoun: "their" },
  { type: "adult", pronoun: "their" },
  { type: "elderly person", pronoun: "their" },
  { type: "office worker", pronoun: "their" },
  { type: "secretary", pronoun: "their" },
  { type: "doctor", pronoun: "their" },
  { type: "nurse", pronoun: "their" },
  { type: "teacher", pronoun: "their" },
  { type: "student", pronoun: "their" },
  { type: "engineer", pronoun: "their" },
  { type: "artist", pronoun: "their" },
  { type: "scientist", pronoun: "their" },
  { type: "musician", pronoun: "their" },
  { type: "chef", pronoun: "their" },
  { type: "driver", pronoun: "their" },
  { type: "athlete", pronoun: "their" },
  { type: "farmer", pronoun: "their" },
  { type: "soldier", pronoun: "their" },
  { type: "pilot", pronoun: "their" },
  { type: "mechanic", pronoun: "their" },
  { type: "cashier", pronoun: "their" },
  { type: "waiter", pronoun: "his" },
  { type: "waitress", pronoun: "her" },
  { type: "businessperson", pronoun: "their" },
  { type: "police officer", pronoun: "their" },
  { type: "firefighter", pronoun: "their" },
  { type: "lawyer", pronoun: "their" },
  { type: "judge", pronoun: "their" },
  { type: "politician", pronoun: "their" },
  { type: "author", pronoun: "their" },
  { type: "poet", pronoun: "their" },
  { type: "programmer", pronoun: "their" },
  { type: "gamer", pronoun: "their" },
  { type: "veterinarian", pronoun: "their" },
  { type: "priest", pronoun: "his" },
  { type: "nun", pronoun: "her" },
  { type: "dentist", pronoun: "their" },
  { type: "barista", pronoun: "their" },
  { type: "gardener", pronoun: "their" },
  { type: "construction worker", pronoun: "their" },
  { type: "delivery driver", pronoun: "their" },
  { type: "dancer", pronoun: "their" },
  { type: "actor", pronoun: "his" },
  { type: "actress", pronoun: "her" },
  { type: "clown", pronoun: "their" },
  { type: "magician", pronoun: "their" },
];
const verbs = [
  { "action": "dropped", "location": true },
  { "action": "ate" },
  { "action": "consumed" },
  { "action": "devoured" },
  { "action": "drank" },
  { "action": "imbibed" },
  { "action": "slurped up" },
  { "action": "inhaled" },
  { "action": "sucked on" },
  { "action": "firmly grasped" },
  { "action": "chewed on" },
  { "action": "sat on" },
  { "action": "looked at" },
  { "action": "was exposed to" },
  { "action": "picked up" },
  { "action": "stood near" },
  { "action": "hugged" },
  { "action": "kicked" },
  { "action": "played with" },
  { "action": "slept on" },
  { "action": "received" },
  { "action": "stole" },
  { "action": "broke" },
  { "action": "touched" },
  { "action": "smelled"},
  { "action": "tasted" },
  { "action": "cooked" },
  { "action": "burned" },
  { "action": "microwaved" },
  { "action": "toasted" },
  { "action": "heated up" },
  { "action": "refrigerated" },
  { "action": "tripped over" },
  { "action": "sniffed" },
  { "action": "spilled", "location": true },
  { "action": "swallowed" },
  { "action": "huffed" },
  { "action": "rubbed", "location": true  },
  { "action": "found", "location": true  },
  { "action": "dragged", "location": true  },
  { "action": "splashed", "location": true },
  { "action": "dribbled", "location": true },
  { "action": "spattered", "location": true },
    { "action": "dripped", "location": true },
  { "action": "microdosed" },
  { "action": "nibbled on" },
  { "action": "partook in" },
  { "action": "snacked on" }
]
const randomObjects = [
  "apple",
  "banana",
  "carrot",
  "sandwich",
  "pizza",
  "soda",
  "phone",
  "water",
  "Coke",
  "Pepsi",
  "Dr. Pepper",
  "Mountain Dew",
  "coffee",
  "milk",
  "cat food",
  "french fry",
  "laptop",
  "e-cigarette",
  "cigarette",
  "vape",
  "pipe",
  "cigar",
  "weed gummy",
  "spider",
  "bug",
  "insect",
  "animal",
  "hotdog",
  "dog",
  "paperclip",
  "chocolate",
  "cookie",
  "cheese",
  "pickle",
  "lead paint",
  "moonshine",
  "caffeine",
  "plant",
  "flower",
  "laxative",
  "benadryl",
  "rubbing alcohol",
  "ibuprofen",
  "beer",
  "rum",
  "substance",
  "powder",
  "throat numbing spray",
  "nacho",
  "vitamin c gummy",
  "cupcake",
  "donut",
  "pasta",
  "steak",
  "rice",
  "chicken",
  "sushi",
  "popcorn",
  "antibiotic",
  "cheeseburger",
  "silica gel packet",
  "energy drink",
  "snowglobe",
  "drain cleaner",
  "whipped cream",
  "burrito",
  "baked potato",
  "pre-workout",
  "anti-psychotic"
];
const descriptiveWords = [
  "suspicious",
  "questionable",
  "dubious",
  "unusual",
  "sketchy",
  "fishy",
  "untrustworthy",
  "mysterious",
  "oddly shaped",
  "odd-smelling",
  "unfamiliar"
];
const bodyParts = [
  "head",
  "hair",
  "eyes",
  "ears",
  "nose",
  "mouth",
  "teeth",
  "tongue",
  "lips",
  "chin",
  "neck",
  "throat",
  "shoulders",
  "arms",
  "elbows",
  "wrists",
  "hands",
  "fingers",
  "nails",
  "chest",
  "heart",
  "lungs",
  "stomach",
  "liver",
  "kidneys",
  "intestines",
  "bladder",
  "pancreas",
  "spleen",
  "spine",
  "ribs",
  "pelvis",
  "hips",
  "legs",
  "knees",
  "ankles",
  "feet",
  "toes",
  "skin",
  "bones",
  "muscles",
  "nervous system",
  "brain",
  "spinal cord",
  "veins",
  "arteries",
  "capillaries",
  "cells",
  "tissues",
  "organs",
  "joints",
  "cartilage",
  "ligaments",
  "blood",
  "sweat glands",
  "tear ducts",
  "thyroid",
  "larynx",
  "pharynx",
  "esophagus",
  "diaphragm",
  "rectum",
  "anus",
  "urethra",
  "vagina",
  "penis",
  "scrotum",
  "breasts",
  "nipples",
  "ovaries",
  "testicles",
  "prostate",
  "uterus",
  "cervix",
  "cornea",
  "retina",
  "pupil",
  "optic nerve",
  "eardrum",
  "taste buds",
  "nasal cavity",
  "palate",
  "uvula",
  "tonsils",
  "adrenals",
  "placenta",
];
const timePeriods = [
  "per second",
  "per minute",
  "per hour",
  "per day",
  "per month",
  "per year",
  "for a second",
  "for a minute",
  "for an hour",
  "for a day",
  "for a week",
  "for a month",
  "for a year",
  "every second",
  "every minute",
  "every hour",
  "every day",
  "every week",
  "every month",
  "every year",
  "for a fortnight",
  "in the morning",
  "in the afternoon",
  "in the evening",
  "in an hour",
  "in a day",
  "in a month",
  "in a year",
  "at night",
  "every few days",
  "every couple of seconds",
  "every couple of hours",
  "every couple of minutes",
  "every couple of days",
];
const relations = [
  "baby's",
  "cousin's",
  "father's",
  "mother's",
  "grandma's",
  "grandpa's",
  "uncle's",
  "aunt's",
  "niece's",
  "nephew's",
  "brother's",
  "sister's",
  "child's",
  "parent's",
  "stepmother's",
  "stepfather's",
  "stepsibling's",
  "in-law's",
  "boss's",
  "colleague's",
  "teammate's",
  "roommate's",
  "friend's",
  "enemy's",
  "neighbor's",
  "partner's",
  "spouse's",
  "teacher's",
  "student's",
  "mentor's",
  "client's",
  "assistant's",
  "coworker's",
  "classmate's",
  "roommate's",
  "companion's",
  "coach's",
  "player's",
  "doctor's",
  "nurse's"
];

const recurrences = [
  'once',
  'twice',
  'three times',
  'four times',
  'five times',
  'repeatedly',
  'over and over',
  'constantly',
  'without end'
]


export function chubbyEmu() {
const subject = people[Math.random() * people.length | 0];
const verb = verbs[Math.random() * verbs.length | 0];
const object = `${Math.random() < 0.2 ? descriptiveWords[Math.random() * descriptiveWords.length | 0] + ' ' : ''}${randomObjects[Math.random() * randomObjects.length | 0]}`;
const number = Math.random() < 0.75 
  ? `${/[aeiou]/i.test(object[0]) ? 'an' : 'a'}` 
  : Math.floor(Math.random() * 1000) + 1;
const bodyPart = bodyParts[Math.random() * bodyParts.length | 0];

const numOrPossessive = (number === 'a' || number === 'an') && Math.random() < 0.45
  ? `${subject.pronoun} ${relations[Math.floor(Math.random() * relations.length)]}`
  : number;

const onBody = verb.location && Math.random() <0.75 ? ` on ${subject.pronoun} ${bodyParts[Math.random() * bodyParts.length | 0]}` : ''

const time = ()=> {
  let period = timePeriods[Math.floor(Math.random() * timePeriods.length)];

  let modPeriod = period.includes('every')
    ? `${recurrences[Math.floor(Math.random() * recurrences.length)]} ${period}`
    : /\b(per|in)\b/.test(period)
    ? `${recurrences[Math.floor(Math.random() * 5)]} ${period}`
    : period;

  return `${Math.random() > 0.5 && !onBody ? ' ' + modPeriod : ''}`

}

const objTime = `${object}${number !== 'a' && number !== 'an' ? (object.endsWith('s') ? 'es' : 's') : ''}${onBody}${time()}`;

const actionModifier = Math.random() < 0.3 ? `accidentally ${verb.action}` : `${verb.action}`

return `${/[aeiou]/i.test(subject.type[0]) ? 'An' : 'A'} ${subject.type} ${actionModifier} ${numOrPossessive} ${objTime}. This is what happened to ${subject.pronoun} ${bodyPart}.`;

}
